version: '3'

tasks:
  default:
    deps: ["build"]

  build:
    aliases: ["b"]
    cmds:
      - go build

  install:
    deps: ["build"]
    aliases: ["i"]
    cmds:
      - 'if {{ eq OS "windows" }}; 
        then powershell cp tgen.exe C:/SANDBOX/APP/bin;
        else cp tgen.exe C:/SANDBOX/APP/bin; fi'

  test:
    aliases: ["t"]
    cmds:
      - go test ./testing
