version: '3'

tasks:
  default:
    deps: ["main"]

  build:
    aliases: ["b"]
    cmds:
      - cmake -B build
      - cmake --build build

  main:
    deps: ["build"]
    cmds:
      - ./build/debug/main.exe