name: Build Go Executable

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu runner (cross-compilation works fine)

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'  # Specify your Go version

      # Step 3: Build the Windows executable
      - name: Build Windows Executable
        run: |
          GOOS=windows GOARCH=amd64 go build -o tgen.exe ./main.go
        # Replace "main.go" with the path to your main Go file if different

      # Step 4: Upload the executable as an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tgen  # Name of the artifact
          path: tgen.exe  # Path to the generated executable