name: Build and Release Windows Executable

# Trigger the workflow only on tagged pushes
on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0.0, v2.0.0, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Go environment (disable caching if no go.sum)
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false  # Disable caching to avoid go.sum warning

      # Step 3: Build the Windows executable
      - name: Build Windows Executable
        run: |
          GOOS=windows GOARCH=amd64 go build -o tgen.exe ./main.go

      # Step 4: Upload the executable as an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tgen
          path: tgen.exe

      # Step 5: Create a GitHub Release
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}  # e.g., v0.1.0
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: tgen.exe